-- Миграция базы данных: Добавление таблиц для системы плагинов
-- Plugin system migration - добавление таблиц для управления плагинами
-- Выполнить эти команды в PostgreSQL как пользователь с правами администратора

-- Основная таблица плагинов
CREATE TABLE IF NOT EXISTS plugins (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    version VARCHAR(50) NOT NULL,
    description TEXT,
    author VARCHAR(255),
    homepage VARCHAR(500),
    license VARCHAR(100),
    package_name VARCHAR(255),
    module_name VARCHAR(255),
    class_name VARCHAR(255),
    is_active BOOLEAN DEFAULT FALSE NOT NULL,
    is_system BOOLEAN DEFAULT FALSE NOT NULL,
    is_installed BOOLEAN DEFAULT FALSE NOT NULL,
    settings_schema JSON,
    default_settings JSON,
    current_settings JSON,
    requires_restart BOOLEAN DEFAULT FALSE NOT NULL,
    dependencies JSON,
    compatibility JSON,
    installed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    installed_by INTEGER
);

-- Таблица логов выполнения действий плагинов
CREATE TABLE IF NOT EXISTS plugin_actions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plugin_id INTEGER NOT NULL REFERENCES plugins(id),
    action_name VARCHAR(255) NOT NULL,
    execution_status VARCHAR(50) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    duration_ms INTEGER,
    parameters JSON,
    result JSON,
    error_message TEXT,
    error_details JSON,
    entity_type VARCHAR(50),
    entity_id INTEGER,
    user_id INTEGER
);

-- Таблица регистрации хуков плагинов
CREATE TABLE IF NOT EXISTS plugin_hooks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plugin_id INTEGER NOT NULL REFERENCES plugins(id),
    hook_type VARCHAR(100) NOT NULL,
    hook_event VARCHAR(100) NOT NULL,
    priority INTEGER DEFAULT 10 NOT NULL,
    conditions JSON,
    settings JSON,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Таблица разрешений плагинов
CREATE TABLE IF NOT EXISTS plugin_permissions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plugin_id INTEGER NOT NULL REFERENCES plugins(id),
    permission_name VARCHAR(255) NOT NULL,
    permission_type VARCHAR(50) NOT NULL, -- 'read', 'write', 'admin'
    resource_type VARCHAR(100) NOT NULL, -- e.g., 'order', 'customer', 'email'
    resource_id VARCHAR(100), -- Specific resource ID or '*' for all
    conditions JSON
);

-- Таблица реестра доступных плагинов (marketplace)
CREATE TABLE IF NOT EXISTS plugin_registry (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,
    author VARCHAR(255),
    version VARCHAR(50) NOT NULL,
    repository_url VARCHAR(500),
    homepage VARCHAR(500),
    documentation_url VARCHAR(500),
    category VARCHAR(100) NOT NULL, -- e.g., 'integration', 'automation', 'report'
    tags JSON,
    min_version VARCHAR(50), -- Minimum system version required
    dependencies JSON, -- Required dependencies
    compatibility JSON, -- Version compatibility
    is_official BOOLEAN DEFAULT FALSE NOT NULL,
    is_featured BOOLEAN DEFAULT FALSE NOT NULL,
    download_count INTEGER DEFAULT 0 NOT NULL,
    rating JSON, -- {average: float, count: int}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Таблица шаблонов плагинов для разработки
CREATE TABLE IF NOT EXISTS plugin_templates (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100) NOT NULL,
    files JSON NOT NULL, -- {filename: content}
    dependencies JSON,
    configuration_schema JSON,
    usage_count INTEGER DEFAULT 0 NOT NULL,
    is_official BOOLEAN DEFAULT FALSE NOT NULL
);

-- Создание индексов для производительности
CREATE INDEX IF NOT EXISTS ix_plugins_name_active ON plugins(name, is_active);
CREATE INDEX IF NOT EXISTS ix_plugins_system_active ON plugins(is_system, is_active);
CREATE INDEX IF NOT EXISTS ix_plugin_actions_plugin_id_started_at ON plugin_actions(plugin_id, started_at);
CREATE INDEX IF NOT EXISTS ix_plugin_hooks_plugin_id_hook_type ON plugin_hooks(plugin_id, hook_type);
CREATE INDEX IF NOT EXISTS ix_plugin_hooks_hook_event ON plugin_hooks(hook_event);
CREATE INDEX IF NOT EXISTS ix_plugin_permissions_plugin_id ON plugin_permissions(plugin_id);
CREATE INDEX IF NOT EXISTS ix_plugin_registry_category ON plugin_registry(category);
CREATE INDEX IF NOT EXISTS ix_plugin_registry_is_featured ON plugin_registry(is_featured);
CREATE INDEX IF NOT EXISTS ix_plugin_templates_category ON plugin_templates(category);

-- Комментарии к таблицам
COMMENT ON TABLE plugins IS 'Основная таблица плагинов системы';
COMMENT ON TABLE plugin_actions IS 'Логирование выполнения действий плагинов';
COMMENT ON TABLE plugin_hooks IS 'Регистрация хуков плагинов для событий системы';
COMMENT ON TABLE plugin_permissions IS 'Разрешения и доступ плагинов к ресурсам';
COMMENT ON TABLE plugin_registry IS 'Реестр доступных плагинов из marketplace';
COMMENT ON TABLE plugin_templates IS 'Шаблоны кода для разработки новых плагинов';

-- Комментарии к колонкам
COMMENT ON COLUMN plugins.name IS 'Уникальное имя плагина для идентификации';
COMMENT ON COLUMN plugins.is_system IS 'Системный плагин (нельзя удалить)';
COMMENT ON COLUMN plugins.settings_schema IS 'JSON Schema для конфигурации плагина';
COMMENT ON COLUMN plugins.requires_restart IS 'Требуется ли перезапуск системы после активации';
COMMENT ON COLUMN plugin_hooks.priority IS 'Приоритет выполнения хука (меньше = выше)';
COMMENT ON COLUMN plugin_registry.category IS 'Категория плагина (integration, automation, report, etc.)';

-- Создание триггера для автоматического обновления updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_plugins_updated_at ON plugins;
CREATE TRIGGER update_plugins_updated_at
    BEFORE UPDATE ON plugins
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_plugin_registry_updated_at ON plugin_registry;
CREATE TRIGGER update_plugin_registry_updated_at
    BEFORE UPDATE ON plugin_registry
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Проверка: Просмотр созданных таблиц
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name LIKE 'plugin%';

-- Проверка: Просмотр структуры основных таблиц
-- \d plugins
-- \d plugin_actions
-- \d plugin_hooks
