"""Initial migration from SQLite to PostgreSQL

Revision ID: 95e7ea14744c
Revises:
Create Date: 2026-01-15 11:39:06.657172

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95e7ea14744c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_settings", sa.Column("admin_contacts", sa.JSON(), nullable=True)
    )
    op.add_column(
        "system_settings", sa.Column("critical_contacts", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_settings", "critical_contacts")
    op.drop_column("system_settings", "admin_contacts")
    # ### end Alembic commands ###
