"""Add company field to customers table

Revision ID: b08ad829700e
Revises: 95e7ea14744c
Create Date: 2026-01-15 12:37:29.180604

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b08ad829700e"
down_revision: Union[str, Sequence[str], None] = "95e7ea14744c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("company", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("idx_triggers_target_stage_id"),
        "triggers",
        ["target_stage_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_tasks_related_order_id"), "tasks", ["related_order_id"], unique=False
    )
    op.create_index(op.f("idx_tasks_created_by"), "tasks", ["created_by"], unique=False)
    op.create_index(
        op.f("idx_tasks_assigned_to"), "tasks", ["assigned_to"], unique=False
    )
    op.create_index(
        op.f("idx_tasks_assigned_created"),
        "tasks",
        ["assigned_to", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_system_settings_id"), table_name="system_settings")
    op.alter_column(
        "system_settings",
        "site_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        existing_server_default=sa.text("'AI CRM System'::character varying"),
    )
    op.drop_column("system_settings", "updated_at")
    op.drop_column("system_settings", "created_at")
    op.drop_column("system_settings", "update_channel")
    op.drop_column("system_settings", "update_check_frequency_hours")
    op.drop_column("system_settings", "auto_update_enabled")
    op.drop_column("system_settings", "backup_path")
    op.drop_column("system_settings", "backup_retention_days")
    op.drop_column("system_settings", "backup_frequency_hours")
    op.drop_column("system_settings", "auto_backup_enabled")
    op.drop_column("system_settings", "push_notifications_enabled")
    op.drop_column("system_settings", "websocket_notifications_enabled")
    op.drop_column("system_settings", "email_notifications_enabled")
    op.drop_column("system_settings", "notifications_enabled")
    op.drop_column("system_settings", "telegram_notification_enabled")
    op.drop_column("system_settings", "telegram_webhook_url")
    op.drop_column("system_settings", "telegram_chat_id")
    op.drop_column("system_settings", "telegram_bot_token")
    op.drop_column("system_settings", "telegram_enabled")
    op.drop_column("system_settings", "smtp_from_name")
    op.drop_column("system_settings", "smtp_from_email")
    op.drop_column("system_settings", "smtp_use_ssl")
    op.drop_column("system_settings", "smtp_use_tls")
    op.drop_column("system_settings", "smtp_password")
    op.drop_column("system_settings", "smtp_user")
    op.drop_column("system_settings", "smtp_port")
    op.drop_column("system_settings", "smtp_host")
    op.drop_column("system_settings", "smtp_enabled")
    op.drop_column("system_settings", "cache_ttl_seconds")
    op.drop_column("system_settings", "redis_port")
    op.drop_column("system_settings", "redis_host")
    op.drop_column("system_settings", "redis_enabled")
    op.drop_column("system_settings", "enable_audit_log")
    op.drop_column("system_settings", "log_retention_days")
    op.drop_column("system_settings", "log_level")
    op.drop_column("system_settings", "performance_thresholds")
    op.drop_column("system_settings", "alert_email_enabled")
    op.drop_column("system_settings", "monitoring_interval_seconds")
    op.drop_column("system_settings", "enable_monitoring")
    op.drop_column("system_settings", "require_2fa")
    op.drop_column("system_settings", "password_min_length")
    op.drop_column("system_settings", "lockout_duration_minutes")
    op.drop_column("system_settings", "max_login_attempts")
    op.drop_column("system_settings", "session_timeout_minutes")
    op.drop_column("system_settings", "support_email")
    op.drop_column("system_settings", "admin_email")
    op.drop_column("system_settings", "site_description")
    op.create_index(
        op.f("idx_stages_process_id"), "stages", ["process_id"], unique=False
    )
    op.create_index(
        op.f("idx_services_category_id"), "services", ["category_id"], unique=False
    )
    op.create_index(
        op.f("idx_service_tags_service_id"),
        "service_tags",
        ["service_id"],
        unique=False,
    )
    op.create_index(op.f("idx_robots_stage_id"), "robots", ["stage_id"], unique=False)
    op.create_index(
        op.f("idx_robot_actions_config_robot_id"),
        "robot_actions_config",
        ["robot_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(
        op.f("idx_production_steps_order_id"),
        "production_steps",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_production_steps_assigned_user_id"),
        "production_steps",
        ["assigned_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_product_tags_product_id"),
        "product_tags",
        ["product_id"],
        unique=False,
    )
    op.create_table_comment(
        "plugins",
        "Основная таблица плагинов системы",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_plugins_name"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_is_installed"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_is_active"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_id"), table_name="plugins")
    op.create_unique_constraint(
        op.f("plugins_name_key"),
        "plugins",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "plugins",
        "requires_restart",
        existing_type=sa.BOOLEAN(),
        comment="Требуется ли перезапуск системы после активации",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "plugins",
        "settings_schema",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="JSON Schema для конфигурации плагина",
        existing_nullable=True,
    )
    op.alter_column(
        "plugins",
        "is_system",
        existing_type=sa.BOOLEAN(),
        comment="Системный плагин (нельзя удалить)",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "plugins",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="Уникальное имя плагина для идентификации",
        existing_nullable=False,
    )
    op.alter_column(
        "plugins",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "plugin_templates",
        "Шаблоны кода для разработки новых плагинов",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_plugin_templates_id"), table_name="plugin_templates")
    op.alter_column(
        "plugin_templates",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "plugin_registry",
        "Реестр доступных плагинов из marketplace",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_plugin_registry_name"), table_name="plugin_registry")
    op.drop_index(op.f("ix_plugin_registry_id"), table_name="plugin_registry")
    op.create_unique_constraint(
        op.f("plugin_registry_name_key"),
        "plugin_registry",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_plugin_registry_is_featured"),
        "plugin_registry",
        ["is_featured"],
        unique=False,
    )
    op.alter_column(
        "plugin_registry",
        "category",
        existing_type=sa.VARCHAR(length=100),
        comment="Категория плагина (integration, automation, report, etc.)",
        existing_nullable=False,
    )
    op.alter_column(
        "plugin_registry",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "plugin_permissions",
        "Разрешения и доступ плагинов к ресурсам",
        existing_comment=None,
        schema=None,
    )
    op.create_foreign_key(
        op.f("plugin_permissions_plugin_id_fkey"),
        "plugin_permissions",
        "plugins",
        ["plugin_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_plugin_permissions_permission_name"), table_name="plugin_permissions"
    )
    op.drop_index(op.f("ix_plugin_permissions_id"), table_name="plugin_permissions")
    op.alter_column(
        "plugin_permissions",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "plugin_hooks",
        "Регистрация хуков плагинов для событий системы",
        existing_comment=None,
        schema=None,
    )
    op.create_foreign_key(
        op.f("plugin_hooks_plugin_id_fkey"),
        "plugin_hooks",
        "plugins",
        ["plugin_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_plugin_hooks_plugin_id"), table_name="plugin_hooks")
    op.drop_index(op.f("ix_plugin_hooks_id"), table_name="plugin_hooks")
    op.drop_index(op.f("ix_plugin_hooks_hook_type"), table_name="plugin_hooks")
    op.create_index(
        op.f("ix_plugin_hooks_plugin_id_hook_type"),
        "plugin_hooks",
        ["plugin_id", "hook_type"],
        unique=False,
    )
    op.alter_column(
        "plugin_hooks",
        "priority",
        existing_type=sa.INTEGER(),
        comment="Приоритет выполнения хука (меньше = выше)",
        existing_nullable=False,
        existing_server_default=sa.text("10"),
    )
    op.alter_column(
        "plugin_hooks",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "plugin_actions",
        "Логирование выполнения действий плагинов",
        existing_comment=None,
        schema=None,
    )
    op.create_foreign_key(
        op.f("plugin_actions_plugin_id_fkey"),
        "plugin_actions",
        "plugins",
        ["plugin_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_plugin_actions_started_at"), table_name="plugin_actions")
    op.drop_index(op.f("ix_plugin_actions_plugin_id"), table_name="plugin_actions")
    op.drop_index(op.f("ix_plugin_actions_id"), table_name="plugin_actions")
    op.create_index(
        op.f("ix_plugin_actions_plugin_id_started_at"),
        "plugin_actions",
        ["plugin_id", "started_at"],
        unique=False,
    )
    op.alter_column(
        "plugin_actions",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(
        op.f("idx_orders_status_created_at"),
        "orders",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(op.f("idx_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        op.f("idx_orders_open"),
        "orders",
        ["id"],
        unique=False,
        postgresql_where="(status <> ALL (ARRAY['CANCELLED'::orderstatus, 'DELIVERED'::orderstatus]))",
    )
    op.create_index(op.f("idx_orders_deadline"), "orders", ["deadline"], unique=False)
    op.create_index(
        op.f("idx_orders_customer_id"), "orders", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("idx_orders_created_at"), "orders", ["created_at"], unique=False
    )
    op.create_index(op.f("idx_customers_phone"), "customers", ["phone"], unique=False)
    op.create_index(op.f("idx_customers_name"), "customers", ["name"], unique=False)
    op.create_index(op.f("idx_customers_email"), "customers", ["email"], unique=False)
    op.create_index(
        op.f("idx_customers_active"),
        "customers",
        ["id"],
        unique=False,
        postgresql_where="(is_deleted = false)",
    )
    op.create_index(
        op.f("idx_communications_customer_id"),
        "communications",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_communications_customer_created"),
        "communications",
        ["customer_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_communications_created_at"),
        "communications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_avito_chat_settings_customer_id"),
        "avito_chat_settings",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_automation_executions_trigger_started"),
        "automation_executions",
        ["trigger_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_automation_executions_trigger_id"),
        "automation_executions",
        ["trigger_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_automation_executions_stage_id"),
        "automation_executions",
        ["stage_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_automation_executions_robot_id"),
        "automation_executions",
        ["robot_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_automation_errors_trigger_id"),
        "automation_errors",
        ["trigger_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_automation_errors_robot_id"),
        "automation_errors",
        ["robot_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_automation_errors_automation_execution_id"),
        "automation_errors",
        ["automation_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_ai_usage_user_month"),
        "ai_usage",
        ["user_id", "month_year"],
        unique=False,
    )
    op.create_index(op.f("idx_ai_usage_user_id"), "ai_usage", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_ai_usage_created_at"), "ai_usage", ["created_at"], unique=False
    )
    op.create_table(
        "email_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "smtp_host", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("smtp_port", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "smtp_username", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("smtp_password", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("smtp_use_tls", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("smtp_use_ssl", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "imap_host", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("imap_port", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "imap_username", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("imap_password", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("imap_use_ssl", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "default_from_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "default_from_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("signature", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "auto_reply_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("auto_reply_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "test_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_settings_pkey")),
    )
    op.create_index(
        op.f("ix_email_settings_user_id"), "email_settings", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_settings_id"), "email_settings", ["id"], unique=False
    )
    op.drop_index(op.f("ix_user_settings_id"), table_name="user_settings")
    op.drop_table("user_settings")
    # ### end Alembic commands ###
